# Numpy Complete Revision


## Python List vs Numpy Array

In [2]:

import numpy as np 
# speed/ Time Comparison
# Python List
import time
a = [i for i in range(100000)]
b = [i for i in range(100000, 200000)]
c = []
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
end1 = time.time()-start
print(end1)

# Numy array
a = np.arange(100000)
b = np.arange(100000, 200000)
start = time.time()
c = a + b
end2 = time.time()-start
print(end2)

print('How much faster is numpy array with python list in this situation', end1/end2)

0.030363082885742188
0.0017430782318115234
How much faster is numpy array with python list in this situation 17.41923129530844


## Creating Numpy Array

In [2]:
### create 1d Array
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(type(a))


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [8]:
# Create 2d Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Create 3d Array
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
# dtype
a = np.array([1,2,3,4,5,6,7,8,9,10], dtype = float)
print(a)
print(a.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [11]:
# arange method
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# reshape
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
a = np.arange(16).reshape(2,2,2,2)
print(a)


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [17]:
# ones and zeros
a = np.ones((3,4))
print(a)
print('\n')
b = np.zeros((4,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# random values between 0 to 1

a = np.random.random((2,2))
print(a)

[[0.83509885 0.53877374]
 [0.03434548 0.68047562]]


In [19]:
a = np.random.randint(1,100, 5)
print(a)

[49 96 30 89 43]


In [25]:
a = np.random.randint(1,20, ((3,3)))
np.random.seed(0)
print(a)

[[13 16  1]
 [ 4  4  8]
 [10 19  5]]


In [31]:
# np.linspace means equal distance points between range 
a = np.linspace(10,100,10, dtype=int)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [27]:
# identity matrix
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Numpy Array Attributes

In [5]:
# ndim 
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [34]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [6]:
# Size 
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [7]:
# Item size Memory me kitni space le rha hai in kbs
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [8]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


## Changing DataType

In [15]:
# astype
print(a1.dtype)
a1 = a1.astype(int)
print(a1.dtype)
a1 = a1.astype(str)
print(a1.dtype)
print(a1)
a1 = a1.astype(bool)
print(a1)

<U21
int64
<U21
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
[ True  True  True  True  True  True  True  True  True  True]


## Aray Operations

In [17]:
n1 = np.arange(12).reshape(3,4)
n2 = np.arange(12,24).reshape(3,4)

print(n1)
print('\n')
print(n2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [18]:
# Scalar Operations
x = n1 * 5
print(x)
x = n1 // 2
print(x)
x = n1 % 2
print(x)
x = n1 - 2
print(x)


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


In [22]:
# Relational 
x = n2 > 15
print(x)

x = n2 == 15
print(x)

[[False False False False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [23]:
# Vector Operations
x = n1 + n2
print(x)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Array Functions

In [35]:
a1 = np.random.random((3,4))
np.random.seed(0)
a1 = np.round(a1 * 100)
print(a1)

[[55. 72. 60. 54.]
 [42. 65. 44. 89.]
 [96. 38. 79. 53.]]


In [36]:
# max/min/sum/product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))


96.0
38.0
747.0
2.0950930532274463e+21


In [40]:
# Axis 
# 0 for column 1 for row

print(np.max(a1, axis=1))
print(np.max(a1, axis=0))
print('\n')
print(np.min(a1, axis=1))
print(np.min(a1, axis=0))
print('\n')


[72. 89. 96.]
[96. 72. 79. 89.]


[54. 42. 38.]
[42. 38. 44. 53.]




In [42]:
# mean/median/mode/std/var
print(np.mean(a1, axis=1))
print('\n')
print(np.median(a1, axis=1))
print('\n')

[60.25 60.   66.5 ]


[57.5 54.5 66. ]




In [44]:
# Dot Product

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

dot = np.dot(a1, a2)
print(dot)


[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [46]:
# log and exp

a = np.log(a2)
b = np.exp(a2)
print(a)
print(b)

[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


In [7]:
# round means nearest
# floor means peche ki taraf jayega
# ceil means upar ki taraf jayega

a1 = np.random.random((3,3))
a1 = a1 * 100
print(a1)
print('\n')
a1 = np.round(a1)
print(a1)
print('\n')
a2 = np.floor(a1)
print(a2)
print('\n')
a3 = np.ceil(a1)
print(a3)

[[58.66122169 42.54809328  0.8930338 ]
 [81.73032671 60.57353412 78.36178092]
 [75.89455267 90.54391575 88.57757866]]


[[59. 43.  1.]
 [82. 61. 78.]
 [76. 91. 89.]]


[[59. 43.  1.]
 [82. 61. 78.]
 [76. 91. 89.]]


[[59. 43.  1.]
 [82. 61. 78.]
 [76. 91. 89.]]


## Indexing and Slicing

In [55]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print('\n')
print(a2)
print('\n')
print(a3)
print('\n')

[0 1 2 3 4 5 6 7 8 9]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]




In [62]:
# Indexing ki practice means single value fetch

print(a1[-1])
print(a2[1, 2])
print(a2[1, 0])
print(a3[1,0,1])
print(a3[0,1,0])
print(a3[0,0,0])
print(a3[1,1,0])

9
6
4
5
2
0
6


In [76]:
# Slicing means multiple values fetch at a time

print(a1[2:5])
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3])

# advanced slicing
# when we want to extract multiple rows and columns
print(a2[[0,2],:][:, [0,3]])
print(a2[[0,2],:][:, [1,3]])


print(a2[1, [0,3]])
print(a2[0:2, 1:])




[2 3 4]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [79]:
# 3d Slicing
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [92]:
print(a3[1])
print('\n')
print(a3[[0,2]])
print('\n')
print(a3[0,1, :])
print('\n')
print(a3[1, :, 1])
print('\n')
print(a3[2, 1:, 1:])
print('\n')
print(a3[[0,2],0, :][:, [0,2]])


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[3 4 5]


[10 13 16]


[[22 23]
 [25 26]]


[[ 0  2]
 [18 20]]


# Iterating

In [93]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print('\n')
print(a2)
print('\n')
print(a3)


[0 1 2 3 4 5 6 7 8 9]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [94]:
for i in a1:
    print(i)
print('\n')
for i in a2:
    print(i)
print('\n')
for i in a3:
    print(i)

0
1
2
3
4
5
6
7
8
9


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [96]:
# nditer convert 2d or 3d array into 1D and iterate them
for i in np.nditer(a2):
    print(i)

print('\n')

for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11


0
1
2
3
4
5
6
7


## Reshaping


In [4]:
#tranpose

a1 = np.arange(12).reshape(3,4)
t1 = np.transpose(a1)
t2 = a1.T
print(t2)
print(t1)


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [13]:
# ravel changes in original array also / flatten it create copy of the original array
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
r = a1.ravel()
print('ravel')
print(a1)
print(r)
r[0] = 50
print(r)
print(a1)
print('\n')
print('flatten')
f = a2.flatten()
print(f)
print(a2)
f[0] = 1000
print(f)
print(a2)




ravel
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[50  1  2  3  4  5  6  7  8  9 10 11]
[[50  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


flatten
[12 13 14 15 16 17 18 19 20 21 22 23]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[1000   13   14   15   16   17   18   19   20   21   22   23]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Stacking

In [14]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [15]:
# hstack
# if we have two array with the shape of 3x4 so output will be 3x8
res1 = np.hstack((a1,a2))
print(res1)


[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [17]:
# vstack
# if we have two array with the shape of 3x4 so output will be 6x4
res2 = np.vstack((a1,a2))
print(res2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Splitting

In [21]:
# horizontal splitting
op1 = np.hsplit(res1,2)
print(op1)
print('\n')
op1 = np.hsplit(res1,4)
print(op1)


[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[12, 13],
       [16, 17],
       [20, 21]]), array([[14, 15],
       [18, 19],
       [22, 23]])]


In [24]:
# vertical split
op2 = np.vsplit(res2,2)
print(op2)
print('\n')
op3 = np.vsplit(res2,3)
print(op3)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


## Advanced Indexing

In [13]:
# Fancy Indexing
a = np.arange(12).reshape(4,3)
print(a)
print("\n")
print(a[[0,2,3]])
print("\n")
b = np.arange(24).reshape(6,4)
print(b)
print("\n")
print(b[[0,2,3,5]])
print("\n")
print(b[:, [0,2,3]])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]


[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [22]:
# Boolean Indexing

np.random.seed(0)
a = np.random.randint(1,100,24).reshape(6,4)
print(a)

# find alll numbers greater than 50

b = a[a > 50]
print(b)

# find out even numbers

c = a[a % 2 == 0]
print(c)

# find alll numbers greater than 50 and are even

c = a[(a > 50) & (a % 2 == 0)]
print(c)

# find all numers that are  divisile by 7

d = a[a % 7 == 0]
print(d)

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]
 [82 38 26 78]]
[65 68 68 84 88 71 89 89 59 66 88 89 82 78]
[48 68 68 10 84 22 88 66 40 88 82 38 26 78]
[68 68 84 88 66 88 82 78]
[84]


## Broadcasting

In [3]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

c = a + b
print(a)
print('\n')
print(b)
print('\n')
print(c)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[0 1 2]


[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [5]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
c = a + b
print(c)


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [6]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
c = a + b
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [7]:
a = np.array([[1]])
b = np.arange(4).reshape(2,2)
c = a + b
print(c)

[[1 2]
 [3 4]]


In [7]:
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

## Missing Values

In [15]:
a = np.array([1,2,3,4,5,np.nan, 6,7,8])
print(a)
b = np.isnan(a)
print(b)
c = a[~np.isnan(a)]
print(c)

[ 1.  2.  3.  4.  5. nan  6.  7.  8.]
[False False False False False  True False False False]
[1. 2. 3. 4. 5. 6. 7. 8.]


In [17]:
arr = np.array([1,2, np.inf, 4, -np.inf])
a = np.isinf(arr)
print(a)
b = arr[~np.isinf(arr)]
print(b)

[False False  True False  True]
[1. 2. 4.]


In [25]:
a = np.array([1,2,3,4,5,np.nan, 6,7,8])
clean = np.nan_to_num(a, nan=10000)
print(clean)

[    1.     2.     3.     4.     5. 10000.     6.     7.     8.]


In [26]:
arr = np.array([1,2, np.inf, 4, -np.inf])
clean = np.nan_to_num(arr, posinf=10000, neginf=-10000)
print(clean)

[     1.      2.  10000.      4. -10000.]


## Functions in Numpy

In [2]:
# sort
# 1D
a = np.random.randint(1,50,10)
b = np.sort(a)
print(a)
print(b)


[15 20 35 15 42  2 19 35 10 32]
[ 2 10 15 15 19 20 32 35 35 42]


In [4]:
# sorting in 2d
a = np.random.randint(1,100,24).reshape(6,4)
print(a)
print('Columns wise sorting')
b = np.sort(a, axis=0)
print(b)
print('Row wise sorting')
c = np.sort(a, axis=1)
print(c)

[[39 17 24 20]
 [ 8 96 81 22]
 [ 8 59 79 86]
 [33 22 97 66]
 [62 92 29 15]
 [88 45 91 19]]
Columns wise sorting
[[ 8 17 24 15]
 [ 8 22 29 19]
 [33 45 79 20]
 [39 59 81 22]
 [62 92 91 66]
 [88 96 97 86]]
Row wise sorting
[[17 20 24 39]
 [ 8 22 81 96]
 [ 8 59 79 86]
 [22 33 66 97]
 [15 29 62 92]
 [19 45 88 91]]


In [9]:
# Append
# 1d
a = np.random.randint(1,50,10)
print(a)
a = np.append(a, -10)
print(a)

[44  4 20 49  1 19 38 43  5  1]
[ 44   4  20  49   1  19  38  43   5   1 -10]


In [16]:
# 2d

a = np.random.randint(1,100,24).reshape(6,4)
print(a)
print('After appending')
a = np.append(a,  [[0,1,2,3]], axis=0 )
print(a)

b = np.append(a, [[0],[0],[0],[0],[0],[0],[0]] , axis=1)
print(b)
# Another way to do that
c = np.append(a, np.ones((7,1)) , axis=1)
print(c)


[[87 50 49 76]
 [94 90 32 84]
 [62 94 61 70]
 [89 29 30 65]
 [69 63 59 30]
 [89 31 96 69]]
After appending
[[87 50 49 76]
 [94 90 32 84]
 [62 94 61 70]
 [89 29 30 65]
 [69 63 59 30]
 [89 31 96 69]
 [ 0  1  2  3]]
[[87 50 49 76  0]
 [94 90 32 84  0]
 [62 94 61 70  0]
 [89 29 30 65  0]
 [69 63 59 30  0]
 [89 31 96 69  0]
 [ 0  1  2  3  0]]
[[87. 50. 49. 76.  1.]
 [94. 90. 32. 84.  1.]
 [62. 94. 61. 70.  1.]
 [89. 29. 30. 65.  1.]
 [69. 63. 59. 30.  1.]
 [89. 31. 96. 69.  1.]
 [ 0.  1.  2.  3.  1.]]


In [24]:
# concatenate
# 1d

a = np.arange(6)
b = np.arange(6,12)

print(a)
print(b)

c = np.concatenate((a,b))
print(c)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
# concatenate
# 2d
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print('After Concatnate')
c = np.concatenate((a,b), axis=0)
print(c)
d = np.concatenate((a,b), axis=1)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
After Concatnate
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [47]:
# Insert at specific position
# 2d
a = np.arange(12).reshape(4,3)
print(a)

b = np.insert(a,1, [100,100,100], axis=0)
print(b)

c = np.insert(b,1,[-100,-100,-100,-100,-100], axis=1)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  0   1   2]
 [100 100 100]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
[[   0 -100    1    2]
 [ 100 -100  100  100]
 [   3 -100    4    5]
 [   6 -100    7    8]
 [   9 -100   10   11]]


In [26]:
# unique
a = np.array([1,2,1,2,3,4,5,4,5,7,9,0,10,])
b = np.unique(a)
print(b)

[ 0  1  2  3  4  5  7  9 10]


In [31]:
# expand_dims ye covert karta hai 1d to 2d 2d to 3d and so on

a = np.array([1,2,1,2,3,4,5,4,5,7,9,0,10,])
print(a.shape)
b = np.expand_dims(a, axis=0)
print(b)
print(b.shape)
c = np.expand_dims(a, axis=1)
print(c)
print(c.shape)

(13,)
[[ 1  2  1  2  3  4  5  4  5  7  9  0 10]]
(1, 13)
[[ 1]
 [ 2]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 4]
 [ 5]
 [ 7]
 [ 9]
 [ 0]
 [10]]
(13, 1)


In [34]:
# np.where means ye return karta hai indices jo condition full fill hogi
# find all indeices whose value greater than 50
a = np.random.randint(1,100,10)
print(a)
b = np.where(a>50)
print(b)
# Replace all values greater than 50 with 0
c = np.where(a>50, 0, a)
print(c)


[52 42 29 93 43 54 71 45 39 64]
(array([0, 3, 5, 6, 9]),)
[ 0 42 29  0 43  0  0 45 39  0]


In [49]:
# np.argmax() ye return kareta hai max element ka index
# np.argmin() ye return kareta hai min element ka index
# 1d
a = np.random.randint(1,100,10)
b = np.argmax(a)
c = np.argmin(a)
print(a)
print(b)
print(c)

[25 71 32 10 88 73 35 54 86 33]
4
3


In [51]:
# 2d
a = np.random.randint(1,100,12).reshape(4,3)
print(a)
b = np.argmax(a, axis=0)
c = np.argmin(a, axis=1)
print(b)
print(c)

[[72 25 23]
 [23 88 78]
 [33 96 99]
 [ 3 86 85]]
[0 2 2]
[2 0 0 0]


In [53]:
# np.cumsum(),commulative sum     np.cumprod ye bilkul wasai hai bas ye product karta hai simple
# 1d
x = np.arange(5)
y = np.cumsum(x)
print(y)

# 2d
a = np.random.randint(1,100,12).reshape(4,3)
print(a)
b = np.cumsum(a, axis=0)
c = np.cumsum(a, axis=1)
print(b)
print(c)

[ 0  1  3  6 10]
[[ 1 81 97]
 [27 83 50]
 [42 67 84]
 [64 22 93]]
[[  1  81  97]
 [ 28 164 147]
 [ 70 231 231]
 [134 253 324]]
[[  1  82 179]
 [ 27 110 160]
 [ 42 109 193]
 [ 64  86 179]]


In [55]:
# np.isin() multiple values check karte hai hmm aik sath  ke us array me hai ya nhi

a = np.arange(10)
item = [10,1,2,3,12]
c = np.isin(a,item)
print(c)
c = a[np.isin(a,item)]
print(c)

[False  True  True  True False False False False False False]
[1 2 3]


In [58]:
# flip reverse the order but maintain its shape
# 1d
a = np.arange(10)
print(a)
b = np.flip(a)
print(b)

# 2d 
a = np.arange(12).reshape(4,3)
print(a)
b = np.flip(a, axis = 0)
print(b)
c = np.flip(a, axis = 1)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [60]:
# np.put() yr direct original array me change karega
a = np.arange(10)
print(a)
np.put(a, [0,1], [100,110])
print(a)

b = np.arange(12).reshape(3,4)
np.put(b, [0,2,11], [100,100,100])
print(b)

[0 1 2 3 4 5 6 7 8 9]
[100 110   2   3   4   5   6   7   8   9]
[[100   1 100   3]
 [  4   5   6   7]
 [  8   9  10 100]]


In [64]:
# np.delete()
# 1d
a = np.arange(10)
print(a)
b = np.delete(a, [0,1])
print(b)

# 2d
print('2d')
a = np.arange(12).reshape(4,3)
print(a)
b = np.delete(a, 0, 0)
print(b)
c = np.delete(a, 0, 1)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
2d
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


## Set Functions

In [71]:
# np.union1d
# np.intersect1d
# np.setdiff1d
# np.setxor1d
# np.in1d

a = np.array([1,2,3,4,5,6,7,8])
b = np.array([3,4,5,6,7,8,8,10])

c = np.union1d(a,b)
print(c)

d = np.intersect1d(a,b)
print(d)

e = np.setdiff1d(a,b)
print(e)

f = np.setxor1d(a,b)
print(f)


[ 1  2  3  4  5  6  7  8 10]
[3 4 5 6 7 8]
[1 2]
[ 1  2 10]
